### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by GuillaumeLacroix** [kmcgill88/admob_flutter#170]
Hi,

I am trying to set up CI/CD on CodeMagic on my project. Everything works fine for Android, however I cannot find a way to build on iOS with admob_flutter. I have reduced my project to a default main file with my full pubspec, and can build and publish if I remove admob_flutter from it, but cannot as soon as I add it again. I tried building with versions **0.3.4** and **1.0.0-beta.2**, which led to the problem corrected by [PR#150](https://github.com/kmcgill88/admob_flutter/pull/150), and subsequently the version linked in the PR comment and **1.0.0-beta.3**, which seems to lead to a link problem ([building_ios.log](https://github.com/kmcgill88/admob_flutter/files/4667625/building_ios.log)). I am building with Flutter 1.17.0 & XCode 11.4.1. I have not been able to build for iOS since I setup CodeMagic a week ago, and am quite clueless as to where to look into from there.
Is it a problem with my configuration or is there any underlying issue?

----------------------------------------------------------------------------------

Flutter doctor _on my own machine_ - I do not have the output of it for CodeMagic:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [version 10.0.18363.836], locale fr-FR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!

-- pubspec for reference --

```
environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flappy_search_bar: 1.4.1
  flutter_local_notifications: 1.3.0
  sqflite: 1.3.0
  package_info: 0.4.0+18
  path_provider: 1.6.7
  http: 0.12.0+4
  intl: ^0.16.0
  cached_network_image: 2.0.0
  sentry: ">=3.0.0 <4.0.0"
  background_fetch: 0.5.5
  flutter_keyboard_visibility: ^0.7.0
  url_launcher: 5.4.2
  global_configuration: 1.5.0
  flutter_calendar_carousel: 1.4.12
  shared_preferences: 0.5.7
  sembast: 2.4.0
  admob_flutter: 1.0.0-beta.3
  firebase_admob: 0.9.3+1
  in_app_purchase: 0.3.2+2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  mockito: any
  flutter_launcher_icons: 0.7.5

```
